### ISSUE TITLE
deprecation warning 

### ISSUE THREAD

**Issue by kad-meedel** [ST-Apps/sonarqube-prometheus-exporter#1]
I think you should have seen this also, but I stil want it to mention.
I am running the docker version of the prometheus exporter tool for sonarqube.
I works ok.

But I get the following deprecation warning at startup:
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  if isinstance(value, collections.MutableMapping):

I am not a developer, otherwise I would have made a suggestion ( pull request ) how to fix it.

**Comment by ST-Apps** [comment]
I'm sorry, I've completely lost access to this account for a while and I've missed everything.
Thanks for reporting, I'm accepting the related PR and releasing a new version.
